/**
 * Subtitle track discovery for the metadata the app already fetches.
 *
 * A typical YouTube video publishes 157 automatic caption languages plus a
 * couple of author-uploaded ones, and the user picks from all of them.
 *
 * The two caption dicts are the bulk of the extraction payload (measured on a
 * real video: 133 KB without them, 624 KB with all of them). The bloat is not
 * the languages, it is the per-language format list: every language repeats
 * seven encodings of the same captions, three of which (`srv1/2/3`) carry the
 * text inline. Keeping one `vtt` entry per language holds all 159 tracks in
 * ~207 KB, and `vtt` is what every language actually publishes, so it is the
 * one format we can always ask for and always convert from.
 *
 * The real subtitle file is written by yt-dlp, not here.
 */

export interface SubtitleTrack {
    /**
     * Unique per track. A language can be published twice - once uploaded by
     * the author and once generated by YouTube - and those are genuinely
     * different files, so the language code alone is not a usable identity.
     */
    key: string;
    /** yt-dlp language code, passed to --sub-langs verbatim. */
    lang: string;
    /** Display label, e.g. "English" or "English (auto)". */
    label: string;
    /** Language name on its own, e.g. "English". */
    langLabel: string;
    /** True for YouTube's automatic captions, false for author-uploaded ones. */
    isAuto: boolean;
    /** Subtitle formats YouTube actually offers for this track. */
    formats: string[];
}

/** Stable identity for a track. */
export function trackKey(lang: string, isAuto: boolean): string {
    return `${isAuto ? 'auto' : 'manual'}:${lang}`;
}

/**
 * Codes `Intl.DisplayNames` cannot name. It resolves 135 of the 159 languages a
 * real video publishes, and these are the remaining ones; without this table
 * they would show up as bare codes in the picker.
 */
const UNLABELLED: Record<string, string> = {
    ab: 'Abkhaz', aa: 'Afar', ba: 'Bashkir', dz: 'Dzongkha', fj: 'Fijian',
    gaa: 'Ga', iu: 'Inuktitut', kl: 'Kalaallisut', kha: 'Khasi',
    lua: 'Luba-Lulua', luo: 'Luo', gv: 'Manx', mfe: 'Mauritian Creole',
    new: 'Nepal Bhasa', os: 'Ossetian', pam: 'Pampanga', rn: 'Rundi',
    sg: 'Sango', crs: 'Cree', ss: 'Swati', bo: 'Tibetan', tum: 'Tumbuka',
    ve: 'Venda', war: 'Waray'
};

const displayNames = (() => {
    try {
        return new Intl.DisplayNames(['en'], { type: 'language' });
    } catch {
        return null;
    }
})();

/**
 * Human name for a language code, e.g. `zh-Hans` -> "Simplified Chinese" and
 * `es-419` -> "Latin American Spanish". Falls back to the raw code rather than
 * hiding the track, so every published language stays selectable.
 */
export function languageLabel(lang: string): string {
    if (!lang) return '';
    if (UNLABELLED[lang]) return UNLABELLED[lang];
    if (displayNames) {
        try {
            const name = displayNames.of(lang);
            if (name && name.toLowerCase() !== lang.toLowerCase()) return name;
        } catch {
            // Not a well-formed tag; fall through to the code.
        }
    }
    return lang;
}

const formatList = (tracks: any[] | undefined): string[] =>
    Array.isArray(tracks) ? tracks.map((t) => String(t?.ext || '')).filter(Boolean) : [];

/** The `live_chat` pseudo-track is a chat log, not a subtitle of the audio. */
const isRealCaptionLang = (lang: string) => !/live_chat/i.test(lang);

/**
 * Every caption track this video publishes, author-uploaded first because
 * those are the accurate ones and there are only ever a handful, then all of
 * YouTube's automatic and translated tracks. A language that appears in both
 * dicts is listed twice on purpose: the author's own track and YouTube's
 * machine translation of it are different files with different quality.
 */
export function buildSubtitleList(raw: any): SubtitleTrack[] {
    const out: SubtitleTrack[] = [];

    const collect = (dict: any, isAuto: boolean) => {
        for (const [lang, tracks] of Object.entries<any>(dict || {})) {
            if (!isRealCaptionLang(lang)) continue;
            const langLabel = languageLabel(lang);
            out.push({
                key: trackKey(lang, isAuto),
                lang,
                langLabel,
                label: isAuto ? `${langLabel} (auto)` : langLabel,
                isAuto,
                formats: formatList(tracks)
            });
        }
    };

    collect(raw?.subtitles, false);
    collect(raw?.automatic_captions, true);

    const byName = (a: SubtitleTrack, b: SubtitleTrack) =>
        a.langLabel.localeCompare(b.langLabel) || a.lang.localeCompare(b.lang);

    return out.sort(byName);
}
